cc_library(
    name = "matcher",
    srcs = [
        "matcher.cc",
    ],
    hdrs = [
        "matcher.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@fmt",
    ],
)

cc_test(
    name = "matcher_test",
    srcs = [
        "matcher_test.cc",
    ],
    deps = [
        ":matcher",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_binary(
    name = "fuzzniq",
    srcs = ["main.cc"],
    visibility = ["//visibility:public"],
    deps = [
        ":matcher",
        "@cli11",
    ],
)
